config/routes.rb
Neon::Application.routes.draw do

  get "inventory/index"
  get "inventory/import"
  resources :timelines, :av_devices, :printers,:idevices, :devices  do
    collection { post :import }
  end
  
  devise_for :users,  :controllers => {:sessions => "sessions"},:path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}  #devise_for :users

  root 'welcome#index'

  
  get "/graph", to: "charts#graph",  as: "graph"
  get "/pie", to: "charts#pie",  as: "pie"
  get "/bar", to: "charts#bar",  as: "bar"
  get "/upload", to: "inventory#index", as: "upload_inventory" 
  post "/inventory/import", to: "inventory#import", as: "import_inventory"

end

app/models/timeline.rb
class Timeline < ActiveRecord::Base
  attr_accessible :device, :date_of_service, :qty
  def self.import(file)
   spreadsheet = Import::Uploader.open_spreadsheet(file)
   spreadsheet.default_sheet = "Computer Timeline"
   Processheet.process_spreadsheet(spreadsheet, self)
  end
  
  def self.process_result(row)
    device = find_by_device(row["device"]) || new
    device.attributes = row.to_hash.slice(*accessible_attributes)
    device.save!
  end
  
  def self.search(search)
    if search
      where('device LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  before_action :set_timeline, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /timelines
  # GET /timelines.json
  def index
    @timelines = Timeline.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
  end

  # GET /timelines/1
  # GET /timelines/1.json
  def show
  end
  
  def import
    Timeline.import(params[:file])
    redirect_to timelines_path, notice: 'Timeline were successfully created.'
  end
  
  # GET /timelines/new
  def new
    @timeline = Timeline.new
  end

  # GET /timelines/1/edit
  def edit
  end

  # POST /timelines
  # POST /timelines.json
  def create
    @timeline = Timeline.new(timeline_params)

    respond_to do |format|
      if @timeline.save
        format.html { redirect_to @timeline, notice: 'Timeline was successfully created.' }
        format.json { render action: 'show', status: :created, location: @timeline }
      else
        format.html { render action: 'new' }
        format.json { render json: @timeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timelines/1
  # PATCH/PUT /timelines/1.json
  def update
    respond_to do |format|
      if @timeline.update(timeline_params)
        format.html { redirect_to @timeline, notice: 'Timeline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @timeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timelines/1
  # DELETE /timelines/1.json
  def destroy
    @timeline.destroy
    respond_to do |format|
      format.html { redirect_to timelines_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timeline
      @timeline = Timeline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timeline_params
      params.require(:timeline).permit(:device, :date_of_service, :qty)
    end
    
    def sort_column
      Timeline.column_names.include?(params[:sort]) ? params[:sort] : "device"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/views/timelines/_form.haml
= form_for @timeline, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :device, :class => 'control-label'
    .controls
      = f.text_field :device, :class => 'text_field'
  .control-group
    = f.label :date_of_service, :class => 'control-label'
    .controls
      = f.text_field :date_of_service, :class => 'text_field'
  .control-group
    = f.label :qty, :class => 'control-label'
    .controls
      = f.text_field :qty, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), timelines_path, :class => 'btn'

app/views/timelines/_timelines.haml
- model_class = Timeline
= hidden_field_tag :direction, params[:direction]
= hidden_field_tag :sort, params[:sort]
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= sortable "device"
      %th= model_class.human_attribute_name(:date_of_service)
      %th= model_class.human_attribute_name(:qty)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @timelines.each do |timeline|
      %tr
        %td= link_to timeline.id, timeline_path(timeline)
        %td= timeline.device
        %td= timeline.date_of_service
        %td= timeline.qty
        %td=l timeline.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_timeline_path(timeline), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), timeline_path(timeline), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

    .pagination{align: 'right'}
      = will_paginate @timelines, renderer: BootstrapPagination::Rails
= link_to t('.new', :default => t("helpers.links.new")), new_timeline_path, :class => 'btn btn-primary'

app/views/timelines/edit.haml
- model_class = Timeline
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/timelines/index.haml
- model_class = Timeline
.page-header
  %h1=t '.title', :default => "Computer Hardware Timeline"
= render partial: '/shared/search', locals:{partial: 'timelines', path: timelines_path}  
= render '/shared/import', file_name: "Timelines.xlsx", import_path: import_timelines_path

app/views/timelines/index.js.haml
$("#devices").html("<%= escape_javascript(render("timelines")) %>");

app/views/timelines/new.haml
- model_class = Timeline
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/timelines/show.haml
- model_class = Timeline
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:device) + ':'
  %br
  = @timeline.device
%p
  %strong= model_class.human_attribute_name(:date_of_service) + ':'
  %br
  = @timeline.date_of_service
%p
  %strong= model_class.human_attribute_name(:qty) + ':'
  %br
  = @timeline.qty

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), timelines_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_timeline_path(@timeline), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), timeline_path(@timeline), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'