config/routes.rb
Neon::Application.routes.draw do

  get "inventory/index"
  get "inventory/import"
  resources :timelines, :av_devices, :printers,:idevices, :devices  do
    collection { post :import }
  end
  
  devise_for :users,  :controllers => {:sessions => "sessions"},:path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}  #devise_for :users

  root 'welcome#index'

  
  get "/graph", to: "charts#graph",  as: "graph"
  get "/pie", to: "charts#pie",  as: "pie"
  get "/bar", to: "charts#bar",  as: "bar"
  get "/upload", to: "inventory#index", as: "upload_inventory" 
  post "/inventory/import", to: "inventory#import", as: "import_inventory"

end

app/models/printer.rb
class Printer < ActiveRecord::Base
  attr_accessible :printer, :location, :host_server, :ip_address, :win_7, :win_xp, :asset_tag, :serial_number, :comment

  validates :asset_tag, uniqueness: true, allow_blank: true
  validates :serial_number, uniqueness: true, allow_blank: true

  def self.import(file)
     spreadsheet = Import::Uploader.open_spreadsheet(file)
     spreadsheet.default_sheet = "Printers"
     Processheet.process_spreadsheet(spreadsheet, self)
  end
   
  def self.process_result(row)
    if colmn = ['serial_number','asset_tag','location'].find {|col| row[col] }
      device = where({"#{colmn}"=> row[colmn], printer: row['printer']}).first || new
      device.attributes = row.to_hash.slice(*accessible_attributes)
      device.save!
    else
      where(row).first_or_create  
    end
  end
  
  def self.search(search)
    if search
      where('printer LIKE ? or host_server LIKE ? or location LIKE ? or serial_number LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/printers_controller.rb
class PrintersController < ApplicationController
  before_action :set_printer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /printers
  # GET /printers.json
  def index
    @printers  = Printer.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
  end

  # GET /printers/1
  # GET /printers/1.json
  def show
  end
  
  def import
    Printer.import(params[:file])
    redirect_to printers_path, notice: 'Printers were successfully created.'
  end

  # GET /printers/new
  def new
    @printer = Printer.new
  end

  # GET /printers/1/edit
  def edit
  end

  # POST /printers
  # POST /printers.json
  def create
    @printer = Printer.new(printer_params)

    respond_to do |format|
      if @printer.save
        format.html { redirect_to @printer, notice: 'Printer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @printer }
      else
        format.html { render action: 'new' }
        format.json { render json: @printer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /printers/1
  # PATCH/PUT /printers/1.json
  def update
    respond_to do |format|
      if @printer.update(printer_params)
        format.html { redirect_to @printer, notice: 'Printer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @printer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /printers/1
  # DELETE /printers/1.json
  def destroy
    @printer.destroy
    respond_to do |format|
      format.html { redirect_to printers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_printer
      @printer = Printer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def printer_params
      params.require(:printer).permit(:printer, :location, :host_server, :ip_address, :win_7, :win_xp, :asset_tag, :serial_number, :comment)
    end
    
    def sort_column
      Printer.column_names.include?(params[:sort]) ? params[:sort] : "printer"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/printers_helper.rb
module PrintersHelper
end

app/views/printers/_form.haml
= form_for @printer, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :printer, :class => 'control-label'
    .controls
      = f.text_field :printer, :class => 'text_field'
  .control-group
    = f.label :location, :class => 'control-label'
    .controls
      = f.text_field :location, :class => 'text_field'
  .control-group
    = f.label :host_server, :class => 'control-label'
    .controls
      = f.text_field :host_server, :class => 'text_field'
  .control-group
    = f.label :ip_address, :class => 'control-label'
    .controls
      = f.text_field :ip_address, :class => 'text_field'
  .control-group
    = f.label :win_7, :class => 'control-label'
    .controls
      = f.text_field :win_7, :class => 'text_field'
  .control-group
    = f.label :win_xp, :class => 'control-label'
    .controls
      = f.text_field :win_xp, :class => 'text_field'
  .control-group
    = f.label :asset_tag, :class => 'control-label'
    .controls
      = f.text_field :asset_tag, :class => 'text_field'
  .control-group
    = f.label :serial_number, :class => 'control-label'
    .controls
      = f.text_field :serial_number, :class => 'text_field'
  .control-group
    = f.label :comment, :class => 'control-label'
    .controls
      = f.text_field :comment, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), printers_path, :class => 'btn'

app/views/printers/_printers.haml
- model_class = Printer
= hidden_field_tag :direction, params[:direction]
= hidden_field_tag :sort, params[:sort]
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= sortable "printer"
      %th= sortable "location"
      %th= sortable "host_server"
      %th= model_class.human_attribute_name(:ip_address)
      %th= model_class.human_attribute_name(:win_7)
      %th= model_class.human_attribute_name(:win_xp)
      %th= model_class.human_attribute_name(:asset_tag)
      %th= sortable "serial_number"
      %th= model_class.human_attribute_name(:comment)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @printers.each do |printer|
      %tr
        %td= link_to printer.id, printer_path(printer)
        %td= printer.printer
        %td= printer.location
        %td= printer.host_server
        %td= printer.ip_address
        %td= printer.win_7
        %td= printer.win_xp
        %td= printer.asset_tag
        %td= printer.serial_number
        %td= printer.comment
        %td=l printer.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_printer_path(printer), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), printer_path(printer), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
    .pagination{align: 'right'}
      = will_paginate @printers, renderer: BootstrapPagination::Rails

= link_to t('.new', :default => t("helpers.links.new")), new_printer_path, :class => 'btn btn-primary'

app/views/printers/edit.haml
- model_class = Printer
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
- @printer.errors.full_messages.each do |message|
  .alert.alert-danger{:role => "alert"}
    = message    
= render :partial => "form"

app/views/printers/index.haml
- model_class = Printer
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
= render partial: '/shared/search', locals:{partial: 'printers', path: printers_path}  
= render '/shared/import', file_name: "Printers.xlsx", import_path: import_printers_path

app/views/printers/index.js.haml
$("#devices").html("<%= escape_javascript(render("printers")) %>");

app/views/printers/new.haml
- model_class = Printer
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
- @printer.errors.full_messages.each do |message|
  .alert.alert-danger{:role => "alert"}
    = message    
= render :partial => "form"

app/views/printers/show.haml
- model_class = Printer
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:printer) + ':'
  %br
  = @printer.printer
%p
  %strong= model_class.human_attribute_name(:location) + ':'
  %br
  = @printer.location
%p
  %strong= model_class.human_attribute_name(:host_server) + ':'
  %br
  = @printer.host_server
%p
  %strong= model_class.human_attribute_name(:ip_address) + ':'
  %br
  = @printer.ip_address
%p
  %strong= model_class.human_attribute_name(:win_7) + ':'
  %br
  = @printer.win_7
%p
  %strong= model_class.human_attribute_name(:win_xp) + ':'
  %br
  = @printer.win_xp
%p
  %strong= model_class.human_attribute_name(:asset_tag) + ':'
  %br
  = @printer.asset_tag
%p
  %strong= model_class.human_attribute_name(:serial_number) + ':'
  %br
  = @printer.serial_number
%p
  %strong= model_class.human_attribute_name(:comment) + ':'
  %br
  = @printer.comment

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), printers_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_printer_path(@printer), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), printer_path(@printer), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'